spring :
  application:
    name : USER-SERVICE-DATA 
  data :
    mongodb :
      url : mongodb://localhost:27017
      database: microservices
  mvc :
    pathmatch :
      matching-strategy : ANT_PATH_MATCHER
      
server:
  port: 8080

  